In [4]:
import numpy as np

In [128]:
np.random.seed(5)

In [129]:
# number of clusters.
k = 3

# size of dataset.
m = 1000
n = 2

In [130]:
X = np.random.randn(m,n)
y = np.random.randn(m)

In [131]:
# define k centroids
C = np.random.randn(k, n)

In [132]:
X[:5]

array([[ 0.44122749, -0.33087015],
       [ 2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112],
       [-0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996]])

In [133]:
C

array([[-2.08948318,  1.27462698],
       [-2.30058089, -1.67090956],
       [-0.83615625, -0.81129715]])

In [134]:
clusters = range(m)

In [135]:
def predict(centroids, point):
    distances = np.linalg.norm(centroids - point, axis=1)
    return np.argmin(distances)

In [136]:
cont = True
run = 0
while cont:
    print "run", run
    run += 1
    new_C = np.zeros(shape=(k,n))
    count = np.zeros(shape=k)
    cont = False
    for i in range(m):
        pred = predict(C, X[i])
        # if a point changes it's cluster, we continue the iteration.
        if pred != clusters[i]:
            cont = True
        clusters[i]=pred
        new_C[pred] += X[i]
        count[pred] += 1
    # calculate new cluster centroids
    count.resize(k,1)
    count = np.repeat(a=count, repeats=n, axis=1)
    C = np.divide(new_C, count)

run 0
run 1
run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9


In [137]:
C

array([[-0.28465138,  1.10911318],
       [-0.84354094, -0.6621314 ],
       [ 0.88943208, -0.28433031]])